// jokes.js - The complete medical humour database
// Structure: { doctors: [50], general: [50], random: [50] } - Total: 150 jokes

const jokes = {
    doctors: [
        { id: 1, text: "Why did the medical student bring a ladder to the ward?\nBecause the consultant said the patient's condition was going downhill." },
        { id: 2, text: "What's the difference between a general surgeon and God?\nGod doesn't think he's a general surgeon." },
        { id: 3, text: "Intern: \"The patient in bed 4 is tachycardic, tachypneic, and hypotensive.\"\nResident: \"Did you give them fluids?\"\nIntern: \"I gave them an encouraging smile.\"" },
        { id: 4, text: "Orthopedics differential diagnosis:\n1. Broken bone.\n2. Bone not broken.\n3. Internal medicine consult." },
        { id: 5, text: "Why do anesthesiologists make great friends?\nThey know exactly how to put you to sleep and they never ask questions." },
        { id: 6, text: "The first rule of night shift:\nYou do not talk about how quiet the night shift is." },
        { id: 7, text: "What’s the most common cause of a medical student sweating?\nThe consultant making eye contact during rounds." },
        { id: 8, text: "Why did the cardiologist get a divorce?\nBecause they couldn't fix a broken heart. Also, 80-hour work weeks." },
        { id: 9, text: "Neurology exams be like: \"Please touch your nose, then touch my finger. Now count backward from 100 by 7s. Now explain the meaning of life.\"" },
        { id: 10, text: "I told my attending I was feeling burned out.\nHe said, \"That's just weakness leaving your body... and your soul leaving your eyes.\"" },
        { id: 11, text: "What do you call a medical student who just passed anatomy?\nA survivor." },
        { id: 12, text: "Psychiatry rounds: Sitting in chairs.\nSurgical rounds: Running down hallways.\nInternal Medicine rounds: Looking at a sodium level for 45 minutes." },
        { id: 13, text: "Why don't surgeons play hide and seek?\nBecause good luck hiding when you insist on sterile lighting and demanding a scalpel." },
        { id: 14, text: "A radiologist's favorite game? Hide and go seek. Usually in a dark room with three monitors." },
        { id: 15, text: "Pediatricians: \"Let's give them a sticker!\"\nSurgeons: \"Let's cut it out.\"\nPathologists: \"Let's put it in a jar.\"" },
        { id: 16, text: "How do you know a patient is a medical professional?\nThey argue with you about their potassium level." },
        { id: 17, text: "Med school taught me that the powerhouse of the cell is the mitochondria, but residency taught me the powerhouse of the hospital is the charge nurse." },
        { id: 18, text: "Why did the artery break up with the vein?\n\"You’re just too superficial and constantly working under pressure.\"" },
        { id: 19, text: "What do you call a doctor who graduated at the bottom of their medical school class?\nDoctor." },
        { id: 20, text: "Dermatology is the only specialty where the standard treatment is either steroids or \"just moisturize.\"" },
        { id: 21, text: "The intern's prayer: \"Lord, grant me the caffeine to change the things I can, and the attending to handle the things I can't.\"" },
        { id: 22, text: "Pharmacology exam: What are the side effects?\nStudent: Nausea, vomiting, diarrhea, and death.\nProfessor: Correct." },
        { id: 23, text: "Why did the white blood cell get a promotion?\nBecause it always went viral." },
        { id: 24, text: "Consultant: \"What's your management plan?\"\nIntern: \"I was planning to consult medicine, surgery, and maybe a priest.\"" },
        { id: 25, text: "If you want to hide something from an orthopedic surgeon, put it in the patient's chart." },
        { id: 26, text: "If you want to hide something from a radiologist, put it on the patient." },
        { id: 27, text: "If you want to hide something from an internist, good luck. They will find it, order three tests for it, and write a 10-page note about it." },
        { id: 28, text: "The hardest part of residency isn't the hours. It's pretending to laugh at the attending's jokes." },
        { id: 29, text: "Blood pressure cuff: *Beeps aggressively*\nNurse: \"Oh, it's just the machine.\"\nIntern: *Writes a 4-page note on hypertensive crisis*" },
        { id: 30, text: "Why do nephrologists love their jobs?\nBecause they’re always dealing with matters of the bean." },
        { id: 31, text: "How to tell if a doctor is an ER doc:\nThey drink cold coffee while sprinting and wearing running shoes." },
        { id: 32, text: "Attending: \"Why are you late?\"\nResident: \"Traffic.\"\nAttending: \"You slept in the hospital.\"\nResident: \"Hallway traffic.\"" },
        { id: 33, text: "Anatomy lab smells like formalin, regret, and the realization that you should have gone to business school." },
        { id: 34, text: "Patient: \"Doctor, will I be able to play the piano after the operation?\"\nSurgeon: \"Yes, of course.\"\nPatient: \"Great, I never knew how before!\"" },
        { id: 35, text: "Why did the CPR mannequin file a complaint?\nHostile work environment and too much chest compression." },
        { id: 36, text: "Gastroenterologist: The only doctor who gets excited when someone says, \"Look what I made!\"" },
        { id: 37, text: "Why is it called an operating 'theater'?\nBecause there's always drama, someone is acting, and the intern is just watching from the back." },
        { id: 38, text: "The best fluid resuscitation for a dehydrated resident is an IV bolus of espresso." },
        { id: 39, text: "ECG shows asystole.\nIntern: \"Should we shock?\"\nCardiologist: \"Only if you want to charge your phone.\"" },
        { id: 40, text: "A neurosurgeon, a general surgeon, and a psychiatrist go duck hunting...\nThe psychiatrist spends 3 hours asking the duck about its mother before shooting." },
        { id: 41, text: "I asked the pulmonologist for a joke.\nHe said, \"I don't have the breath for it.\"" },
        { id: 42, text: "Why did the virus break up with the bacteria?\nIt said, \"We have no culture.\"" },
        { id: 43, text: "An OB/GYN’s favorite phrase: \"Push!\"\nA Med Student’s favorite phrase: \"Can I go home now?\"" },
        { id: 44, text: "Patient has a fever of unknown origin.\nInternal Medicine: Let's do a million dollar workup.\nSurgery: Is there pus? No? Not my problem." },
        { id: 45, text: "Why don't ophthalmologists ever get lost?\nThey have excellent peripheral vision." },
        { id: 46, text: "The most dangerous thing in the hospital is a first-year resident with an idea." },
        { id: 47, text: "The second most dangerous thing is an attending with a piece of chalk." },
        { id: 48, text: "What's the difference between a GP and a specialist?\nA GP treats what you have. A specialist thinks you have what they treat." },
        { id: 49, text: "Why was the microbiology student crying?\nThey failed the culture test." },
        { id: 50, text: "Medical school: Where you learn 10,000 diseases, only to see the same 5 in the ER every single day." }
    ],

    general: [
        { id: 51, text: "I told my doctor I broke my arm in two places.\nHe told me to stop going to those places." },
        { id: 52, text: "Patient: \"Doctor, I think I'm a moth.\"\nDoctor: \"You need a psychiatrist, why did you come here?\"\nPatient: \"The light was on.\"" },
        { id: 53, text: "Why did the man put his money in the freezer?\nHe wanted cold hard cash to pay his medical bills." },
        { id: 54, text: "My doctor told me to watch my drinking.\nNow I drink in front of a mirror." },
        { id: 55, text: "Why did the banana go to the doctor?\nBecause he wasn't peeling well." },
        { id: 56, text: "I looked up my symptoms on WebMD.\nTurns out I have three days to live and I’m also pregnant. I'm a guy." },
        { id: 57, text: "An apple a day keeps the doctor away.\nIf you throw it hard enough." },
        { id: 58, text: "Doctor: \"You're overweight.\"\nPatient: \"I want a second opinion.\"\nDoctor: \"You're ugly too.\"" },
        { id: 59, text: "What do you call a fake noodle?\nAn impasta. (Also what I feel like when WebMD tells me I'm a doctor)." },
        { id: 60, text: "Why did the mattress go to the doctor?\nIt had spring fever." },
        { id: 61, text: "A man goes to the doctor and says, \"Doctor, wherever I touch, it hurts.\"\nThe doctor says, \"Your finger is broken.\"" },
        { id: 62, text: "I asked the pharmacist which painkiller is best.\nHe said, \"Winning the lottery, but ibuprofen is cheaper.\"" },
        { id: 63, text: "Doctor: \"Take one of these pills every day for the rest of your life.\"\nPatient: \"But there are only three pills here?\"\nDoctor: \"Exactly.\"" },
        { id: 64, text: "Why did the computer go to the doctor?\nIt had a virus." },
        { id: 65, text: "Waiting rooms are called waiting rooms because if they were called 'Sit Here for Two Hours Rooms', nobody would come." },
        { id: 66, text: "I told the doctor I hear ringing in my ears.\nHe said, \"Don't answer it.\"" },
        { id: 67, text: "My doctor wrote me a prescription.\nI took it to the pharmacy. The pharmacist looked at it and said, \"I'm sorry, we don't sell squiggly lines.\"" },
        { id: 68, text: "Patient: \"Will this ointment clear up my spots?\"\nDoctor: \"I never make rash promises.\"" },
        { id: 69, text: "What’s the best time to go to the dentist?\nTooth-hurty." },
        { id: 70, text: "I went to the doctor because I swallowed a clock.\nHe said, \"Don't worry, it's time-consuming, but it will pass.\"" },
        { id: 71, text: "Doctor: \"Your X-ray showed a broken rib.\"\nPatient: \"Oh no, what did you do?\"\nDoctor: \"We fixed it with Photoshop.\"" },
        { id: 72, text: "Why did the cookie go to the hospital?\nBecause it felt crummy." },
        { id: 73, text: "My grandmother walked 5 miles a day when she was 60.\nShe's 97 today, and we don't know where the heck she is." },
        { id: 74, text: "Nurse: \"Blood type?\"\nPatient: \"Red.\"" },
        { id: 75, text: "I told the doctor I feel like a deck of cards.\nHe said, \"I'll deal with you later.\"" },
        { id: 76, text: "Why did the invisible man turn down the doctor's appointment?\nHe couldn't see himself going." },
        { id: 77, text: "A guy walks into the doctor's office with a carrot in his ear and a celery stick in his nose.\nDoctor: \"You're not eating right.\"" },
        { id: 78, text: "Hospital gowns: Because who doesn't love an unexpected breeze?" },
        { id: 79, text: "Doctor: \"Are you getting enough exercise?\"\nMe: \"Does running late count?\"" },
        { id: 80, text: "I told my doctor I have a problem with stealing things.\nHe said, \"Take these pills. If they don't work, get me a new TV.\"" },
        { id: 81, text: "My doctor told me to eat more greens.\nSo I bought mint chocolate chip ice cream." },
        { id: 82, text: "Why do nurses bring red crayons to work?\nIn case they have to draw blood." },
        { id: 83, text: "I tried to explain my symptoms to the receptionist, but she put me on hold.\nGuess I'll just heal naturally." },
        { id: 84, text: "Doctor: \"Do you have a medical history?\"\nMe: \"Yes, I’ve been sick before.\"" },
        { id: 85, text: "Going to the doctor is just paying someone $200 to tell you to drink more water." },
        { id: 86, text: "I got a medical bill for $5,000 for a band-aid.\nAt least the band-aid stopped the bleeding from my wallet." },
        { id: 87, text: "Why did the skeleton go to the hospital?\nHe was feeling a bit bone-tired." },
        { id: 88, text: "Patient: \"Doctor, I'm shrinking!\"\nDoctor: \"Well, you'll just have to be a little patient.\"" },
        { id: 89, text: "My eye doctor told me I was colorblind.\nThat came right out of the purple." },
        { id: 90, text: "Doctor: \"You need an organ transplant.\"\nMe: \"Can I get a piano instead?\"" },
        { id: 91, text: "I asked the nurse if it was going to hurt.\nShe said, \"Only when you get the bill.\"" },
        { id: 92, text: "My doctor said I need to cut out carbs.\nSo I cut the bread in half before eating it." },
        { id: 93, text: "Why did the tomato go to the doctor?\nBecause it was a little red in the face." },
        { id: 94, text: "Doctor: \"You need to rest.\"\nMe: \"I have three kids.\"\nDoctor: \"Then you need a miracle.\"" },
        { id: 95, text: "I told my therapist I have a fear of elevators.\nShe told me to take steps to avoid them." },
        { id: 96, text: "A sneeze is just your face throwing up air." },
        { id: 97, text: "Doctor: \"We need to run some tests.\"\nMe: \"Can we walk them instead? I'm tired.\"" },
        { id: 98, text: "Pharmacy drive-thrus are great until you realize the person ahead of you is buying a new liver." },
        { id: 99, text: "I bought a step tracker.\nTurns out, walking from the couch to the fridge is only 15 steps." },
        { id: 100, text: "What do you call a doctor who fixes websites?\nA URL-ologist." }
    ],

    random: [
        { id: 101, text: "Healthcare is the only industry where they ask you to arrive 15 minutes early so you can wait an hour." },
        { id: 102, text: "Medical charts are just diaries about how bad someone's body is at doing its job." },
        { id: 103, text: "I asked the hospital if they had Wi-Fi.\nThey said yes, but it costs one kidney per hour." },
        { id: 104, text: "Surgeons are just mechanics who are not allowed to turn off the engine while they work." },
        { id: 105, text: "A scalpel is just a very confident knife." },
        { id: 106, text: "Vitamins are just DLC for your immune system." },
        { id: 107, text: "The human body is amazing. It can heal a cut in a week, but if you sleep with your neck at a 2-degree angle, you are paralyzed for 3 days." },
        { id: 108, text: "A fever is just your body turning the thermostat up to roast the intruders." },
        { id: 109, text: "CPR is just necromancy that actually works." },
        { id: 110, text: "Anesthesia is just medical time travel." },
        { id: 111, text: "Bones are just internal armor that breaks if you trip over a rug." },
        { id: 112, text: "The appendix is the body's self-destruct button, and nobody knows why it's there." },
        { id: 113, text: "Sneezing is a software reset for your nose." },
        { id: 114, text: "Hospitals are the only place where getting a 'negative' result is the best news ever." },
        { id: 115, text: "Dentists: The only people who tell you to open your mouth and then get mad when you try to talk." },
        { id: 116, text: "If you think about it, blood tests are just pop quizzes for your organs." },
        { id: 117, text: "Allergies are your immune system being a drama queen about dust." },
        { id: 118, text: "The stethoscope is the medical equivalent of a 'Do Not Disturb' sign." },
        { id: 119, text: "Phlebotomists are just socially acceptable vampires." },
        { id: 120, text: "The liver is the body's IT department. It filters out all the spam you drink." },
        { id: 121, text: "A cast is just a plaster hug for your broken bone." },
        { id: 122, text: "X-rays are just selfies of your skeleton." },
        { id: 123, text: "Cough drops are just candy that tastes like medicine so you don't eat them all at once." },
        { id: 124, text: "Your stomach thinks all potatoes are mashed." },
        { id: 125, text: "Adrenaline is just natural energy drink made of pure panic." },
        { id: 126, text: "The spleen is the body's mystery box. Doctors just nod and pretend they know what it does." },
        { id: 127, text: "Scrubs are just hospital-approved pajamas." },
        { id: 128, text: "Medical tape is a paradox: it sticks to everything except the bandage." },
        { id: 129, text: "The tongue is the only muscle you can see without surgery, which is honestly kind of gross." },
        { id: 130, text: "A placebo is just the doctor gaslighting your body into healing itself." },
        { id: 131, text: "Why do we call it an 'operating room' when it's the only room where the patient is definitely not operating?" },
        { id: 132, text: "If tomatoes are a fruit, then ketchup is a smoothie, which means eating fries is a health cleanse." },
        { id: 133, text: "The brain is the only organ that named itself." },
        { id: 134, text: "Insomnia is your brain deciding it's time to review every mistake you made since 2014." },
        { id: 135, text: "An MRI machine is just a very loud, very expensive metal donut." },
        { id: 136, text: "Tonsils are just the body's bouncers that get fired and removed when they cause too much trouble." },
        { id: 137, text: "A headache is just your brain feeling itself." },
        { id: 138, text: "When you get an ultrasound, they just rub warm jelly on you like you're a human piece of toast." },
        { id: 139, text: "Therapy is just paying a premium to complain with professional boundaries." },
        { id: 140, text: "The funny bone is neither funny nor a bone. It's a nerve that loves chaos." },
        { id: 141, text: "A heart attack is just your heart saying, 'I quit!'" },
        { id: 142, text: "A blister is just your shoe demanding rent in the form of skin." },
        { id: 143, text: "Bruises are just your skin keeping receipts of your clumsiness." },
        { id: 144, text: "The waiting room magazines are actually prescribed by doctors to test your tolerance for boredom." },
        { id: 145, text: "Crutches are just arm-legs for when your leg-legs fail." },
        { id: 146, text: "If we can transplant hearts, why hasn't someone invented a transplant for common sense?" },
        { id: 147, text: "A yawn is just a silent scream for coffee." },
        { id: 148, text: "Stitches are just sewing classes applied to human skin." },
        { id: 149, text: "Your immune system is a microscopic army that occasionally attacks a peanut by mistake." },
        { id: 150, text: "Medicine is the art of amusing the patient while nature cures the disease." }
    ]
};